# Generated by Django 4.0.5 on 2022-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_players'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(null=True, to='teams.team'),
        ),
    ]
