# Generated by Django 4.0.5 on 2022-07-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_players'),
        ('tournaments', '0002_alter_tournament_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(to='teams.team'),
        ),
    ]
