# Generated by Django 4.0.5 on 2022-07-19 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0005_remove_team_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.team')),
                ('team_adversary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_adversary', to='teams.team')),
            ],
        ),
    ]
