# Generated by Django 4.0.5 on 2022-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_alter_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
