# Generated by Django 4.0.5 on 2022-07-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_alter_event_date_time_alter_match_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_time',
            new_name='date',
        ),
    ]
