# Generated by Django 4.0.5 on 2022-07-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_rename_date_time_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
