# Generated by Django 4.0.5 on 2022-07-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_player_team'),
        ('teams', '0002_team_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='players.player'),
        ),
    ]
