# Generated by Django 4.0.5 on 2022-07-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_tournament'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='Event',
        ),
    ]
