# Generated by Django 4.0.5 on 2022-07-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_created_at_team_updated_at'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together={('team', 'tournament')},
        ),
    ]
