# Generated by Django 4.0.5 on 2022-07-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
