# Generated by Django 4.0.5 on 2022-07-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_team'),
        ('teams', '0005_remove_team_players'),
        ('transfers', '0002_alter_transfer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='players.player'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='teams.team'),
        ),
    ]
