# Generated by Django 4.0.5 on 2022-07-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_players'),
        ('matches', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_adversary',
        ),
        migrations.AddField(
            model_name='match',
            name='team_away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_away', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_home', to='teams.team'),
        ),
    ]
