# Generated by Django 4.0.5 on 2022-07-22 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_players'),
        ('matches', '0006_remove_match_team_remove_match_team_adversary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_away', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_home', to='teams.team'),
        ),
    ]
