# Generated by Django 4.0.5 on 2022-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_alter_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('start', 'Start'), ('goal', 'Goal'), ('break', 'Break'), ('addition', 'Addition'), ('replacement', 'Replacement'), ('warning', 'Warning'), ('end', 'End')], default='start', max_length=100),
        ),
    ]
