# Generated by Django 4.0.5 on 2022-07-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_remove_event_title_event_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
