# Generated by Django 4.0.5 on 2022-06-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birth', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
            ],
        ),
    ]
